// import pattern from '../../assets/svg/background-pattern-3.svg';
export default {
    headerTop: {
        background: {
            height: "auto",
            backgroundImage: "linear-gradient(to bottom, #df5a34, #8651aa)",
        },
        spaceBar: {
            width: "auto",
            height: "50px",
        },
        smallSpaceBar: {
            width: "auto",
            height: "10px",
        },
        appBar: {
            width: "1440px",
            height: "90px",
            margin: "auto",
            customize: {
                width:"14.285%",
                height: "70px",
                display: "inline-flex",
            },
            apps: {
                width:"14.285%",
                height: "70px",
                display: "inline-flex",
            },
            stories: {
                width:"14.285%",
                height: "70px",
                display: "inline-flex",
            },
            gstickers: {
                width:"14.285%",
                height: "70px",
                // backgroundColor: "green",
                display: "inline-flex",
                margin: "auto",
                padding: "auto",
                background: {
                    // width: "263.1px",
                    width: "100%",
                    // height: "86.3px",
                    height: "100%",
                    borderRadius: "11.7px",
                    backgroundColor: "#ffffff",
                    marginTop: "0px",
                },
                image: {

                    width: "164px",
                    // height: "38px",
                    objectFit: "contain",
                    // padding: "auto",
                    marginLeft: "10%",
                    // marginBottom: "auto",
                    marginTop: "8%",
                    display: "inline-flex",
                },
                logoImage: {
                    width: "85%",
                    objectFit: "contain",
                    padding: "11px 0px",
                    // marginTop:    "11px",
                    // marginBottom: "11px",
                    display: "inline-flex",
                },
            },
            shadowText: {

                fontSize: "24px",
                fontWeight: "800",
                letterSpacing: "-1.5px",
                // textAlign: "center",
                margin: "auto",
                color: "#ffffff",
                textShadow: "0 1px 6px rgba(0, 0, 0, 0.5)",
            },
            text: {

                // fontSize: "24px",
                fontSize: "20px",
                fontWeight: "bold",
                letterSpacing: "-1.5px",
                // textAlign: "center",
                margin: "auto",
                // colors: "#ffffff",
            },
            smallShadowText: {

                fontSize: "20px",
                fontWeight: "800",
                letterSpacing: "-1.5px",
                // textAlign: "center",
                margin: "auto",
                color: "#ffffff",
                textShadow: "0 1px 6px rgba(0, 0, 0, 0.5)",
            },
            smallText: {

                fontSize: "25px",
                fontWeight: "800",
                letterSpacing: "-1.5px",
                // textAlign: "center",
                margin: "auto",
                // paddingLeft: "15px",
                // colors: "#ffffff",
            },
        },
    },

    appHeader: {
    background: {
        height: "auto",
        backgroundImage: "linear-gradient(to bottom, #df5a34, #8651aa)",
    },
    pattern: {
        width: "100%",
        height: "auto",
        // backgroundImage: "url(" + pattern + ")",
    },
    spaceBar: {
        width: "auto",
        height: "50px",
    },
    smallSpaceBar: {
        width: "auto",
        height: "20px",
    },
    appBar: {
        width: "1440px",
        height: "90px",
        margin: "auto",
        customize: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        apps: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        stories: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        gstickers: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
            margin: "auto",
            padding: "auto",
            background: {
                width: "100%",
                height: "100%",
                borderRadius: "11.7px",
                backgroundColor: "#ffffff",
                marginTop: "0px",
            },
            image: {

                width: "164px",
                objectFit: "contain",
                marginLeft: "10%",
                marginTop: "8%",
                display: "inline-flex",
            },
            logoImage: {
                width: "90%",
                objectFit: "contain",
                marginTop: "3px",
                marginBottom: "3px",
                display: "inline-flex",
            },
        },
        forCreators: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        forBrands: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        merch: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        shadowText: {
            fontFamily: "Montserrat",
            fontSize: "24px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            margin: "auto",
            color: "#ffffff",
            textShadow: "0 1px 6px rgba(0, 0, 0, 0.5)",
        },
        text: {
            fontFamily: "Montserrat",
            fontSize: "24px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            margin: "auto",
            color: "#ffffff",
        },
        smallShadowText: {
            fontFamily: "Montserrat",
            fontSize: "14px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            margin: "auto",
            color: "#ffffff",
            textShadow: "0 1px 6px rgba(0, 0, 0, 0.5)",
        },
        smallText: {
            fontFamily: "Montserrat",
            fontSize: "14px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            margin: "auto",
            color: "#ffffff",
        }
    },
    bigText: {
        width: "70%",
        height: "auto",
        fontFamily: "Montserrat",
        fontSize: "40px",
        fontWeight: "bold",
        letterSpacing: "-2.5px",
        textAlign: "center",
        color: "#ffffff",
        textShadow: "0 1px 2px rgba(0, 0, 0, 0.5)",
        marginBottom: "20px",
        marginLeft: "auto",
        marginRight: "auto",
        objectFit: "contain",
        display: "block",
    },
        bigText_forSmallScreens: {
            width: "70%",
            height: "auto",
            fontFamily: "Montserrat",
            fontSize: "30px",
            fontWeight: "bold",
            letterSpacing: "-2.5px",
            textAlign: "center",
            color: "#ffffff",
            textShadow: "0 1px 2px rgba(0, 0, 0, 0.5)",
            marginBottom: "20px",
            marginLeft: "auto",
            marginRight: "auto",
            objectFit: "contain",
            display: "block",
        },
    download: {
        width: "257px",
        height: "37px",
        fontFamily: "Montserrat",
        fontSize: "30px",
        fontWeight: "bold",
        letterSpacing: "-1.8px",
        textAlign: "center",
        color: "#ffffff",
    },
    appBadges: {
        width: "90%",
        height: "auto",
        marginTop: "5px",
        marginBottom: "5px",
        marginRight: "5%",
        marginLeft: "5%",
    },
},

    customizeHeader: {
    background: {
        height: "auto",
        backgroundImage: "linear-gradient(to bottom, #df5a34, #8651aa)",
    },
    pattern: {
        width: "100%",
        height: "auto",
        // backgroundImage: "url(" + pattern + ")",
    },
    spaceBar: {
        width: "auto",
        height: "50px",
    },
    smallSpaceBar: {
        width: "auto",
        height: "20px",
    },
    appBar: {
        width: "1440px",
        height: "90px",
        margin: "auto",
        customize: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        apps: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        stories: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        gstickers: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
            margin: "auto",
            padding: "auto",
            background: {
                width: "100%",
                height: "100%",
                borderRadius: "11.7px",
                backgroundColor: "#ffffff",
                marginTop: "0px",
            },
            image: {

                width: "164px",
                objectFit: "contain",
                marginLeft: "10%",
                marginTop: "8%",
                display: "inline-flex",
            },
            logoImage: {
                width: "90%",
                objectFit: "contain",
                marginTop: "3px",
                marginBottom: "3px",
                display: "inline-flex",
            },
        },
        forCreators: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        forBrands: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        merch: {
            width:"14.285%",
            height: "70px",
            display: "inline-flex",
        },
        shadowText: {
            fontFamily: "Montserrat",
            fontSize: "24px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            margin: "auto",
            color: "#ffffff",
            textShadow: "0 1px 6px rgba(0, 0, 0, 0.5)",
        },
        text: {
            fontFamily: "Montserrat",
            fontSize: "24px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            margin: "auto",
            color: "#ffffff",
        },
        smallShadowText: {
            fontFamily: "Montserrat",
            fontSize: "14px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            margin: "auto",
            color: "#ffffff",
            textShadow: "0 1px 6px rgba(0, 0, 0, 0.5)",
        },
        smallText: {
            fontFamily: "Montserrat",
            fontSize: "14px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            margin: "auto",
            color: "#ffffff",
        }
    },
    bigText: {
        width: "70%",
        height: "auto",
        fontFamily: "Montserrat",
        fontSize: "40px",
        fontWeight: "bold",
        letterSpacing: "-2.5px",
        textAlign: "center",
        color: "#ffffff",
        textShadow: "0 1px 2px rgba(0, 0, 0, 0.5)",
        marginBottom: "20px",
        marginLeft: "auto",
        marginRight: "auto",
        objectFit: "contain",
        display: "block",
    },
    download: {
        width: "257px",
        height: "37px",
        fontFamily: "Montserrat",
        fontSize: "30px",
        fontWeight: "bold",
        letterSpacing: "-1.8px",
        textAlign: "center",
        color: "#ffffff",
    },
    appBadges: {
        width: "90%",
        height: "auto",
        marginTop: "5px",
        marginBottom: "5px",
        marginRight: "5%",
        marginLeft: "5%",
    },
},

    header: {
    background: {
        height: "auto",
        backgroundImage: "linear-gradient(to bottom, #df5a34, #8651aa)",
        // backgroundColor: "yellow",
    },
    pattern: {
        width: "100%",
        height: "auto",
        // backgroundImage: "url(" + pattern + ")",
    },
    spaceBar: {
        width: "auto",
        height: "50px",
    },
    appBar: {
        width: "1440px",
        height: "90px",
        margin: "auto",
        // backgroundColor: "lightgrey",
        customize: {
            width:"14.285%",
            height: "70px",
            // backgroundColor: "red",
            display: "inline-flex",
        },
        apps: {
            width:"14.285%",
            height: "70px",
            // backgroundColor: "orange",
            display: "inline-flex",
        },
        stories: {
            width:"14.285%",
            height: "70px",
            // backgroundColor: "yellow",
            display: "inline-flex",
        },
        gstickers: {
            width:"14.285%",
            height: "70px",
            // backgroundColor: "green",
            display: "inline-flex",
            margin: "auto",
            padding: "auto",
            background: {
                // width: "263.1px",
                width: "100%",
                // height: "86.3px",
                height: "100%",
                borderRadius: "11.7px",
                backgroundColor: "#ffffff",
                marginTop: "0px",
            },
            image: {

                width: "164px",
                // height: "38px",
                objectFit: "contain",
                // padding: "auto",
                marginLeft: "10%",
                // marginBottom: "auto",
                marginTop: "8%",
                display: "inline-flex",
            },
            logoImage: {
                width: "90%",
                objectFit: "contain",
                marginTop: "3px",
                marginBottom: "3px",
                display: "inline-flex",
            },
        },
        forCreators: {
            width:"14.285%",
            height: "70px",
            // backgroundColor: "blue",
            display: "inline-flex",
        },
        forBrands: {
            width:"14.285%",
            height: "70px",
            // backgroundColor: "indigo",
            display: "inline-flex",
        },
        merch: {
            width:"14.285%",
            height: "70px",
            // backgroundColor: "purple",
            display: "inline-flex",
        },
        shadowText: {
            fontFamily: "Montserrat",
            fontSize: "24px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            // textAlign: "center",
            margin: "auto",
            color: "#ffffff",
            textShadow: "0 1px 6px rgba(0, 0, 0, 0.5)",
        },
        text: {
            fontFamily: "Montserrat",
            fontSize: "24px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            // textAlign: "center",
            margin: "auto",
            color: "#ffffff",
        },
        smallShadowText: {
            fontFamily: "Montserrat",
            fontSize: "14px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            // textAlign: "center",
            margin: "auto",
            color: "#ffffff",
            textShadow: "0 1px 6px rgba(0, 0, 0, 0.5)",
        },
        smallText: {
            fontFamily: "Montserrat",
            fontSize: "14px",
            fontWeight: "800",
            letterSpacing: "-1.5px",
            // textAlign: "center",
            margin: "auto",
            color: "#ffffff",
        }
    },
    kwekuAndAma: {
        width: "90%",
        height: "auto",
        fontFamily: "Montserrat",
        fontSize: "30px",
        fontWeight: "bold",
        letterSpacing: "-2.5px",
        textAlign: "center",
        color: "#ffffff",
        textShadow: "0 1px 2px rgba(0, 0, 0, 0.5)",
        marginBottom: "20px",
        // padding: "20px",
        // backgroundColor: "lightpink",
        marginLeft: "auto",
        marginRight: "auto",
        objectFit: "contain",
        display: "block",
    },
    content: {
        background: {
            // width: "100%",
            height: "auto",
            opacity: "0.98",
            borderRadius: "15px",
            backgroundColor: "#ffffff",
            paddingBottom: "10px",
        },
        artwork: {
            width: "90%",
            height: "auto",
            marginLeft: "auto",
            marginRight: "auto",
            objectFit: "contain",
            display: "block",
        },
        downloadLinks: {
            width: "95%",
            height: "80px",
            opacity: "0.97",
            borderRadius: "15px",
            // backgroundColor: "#ffffff",
            border: "solid 1.5px #c7c7c7",
            marginTop: "5px",
            // marginBottom: "5px",
            marginLeft: "auto",
            marginRight: "auto",
        },
        ghanaTok: {
            width: "40%",
            height: "auto",
            fontFamily: "Montserrat",
            fontSize: "42px",
            fontWeight: "bold",
            letterSpacing: "-2.5px",
            textAlign: "left",
            color:"#292929",
            marginTop: "17px",
            marginBottom: "17px",
            marginRight: "37px",
            marginLeft: "47px",
            display: "block",
            float: "left",
        },
        appBadges: {
            width: "20%",
            height: "auto",
            display: "block",
            float: "left",
            marginTop: "10px",
            // marginBottom: "25px",
            marginRight: "15px",
            // marginLeft: "25px",
        },
    },
},

    variableHeader: {
        background: {
            height: "auto",
            backgroundImage: "linear-gradient(to bottom, #df5a34, #8651aa)",
        },
        pattern: {
            width: "100%",
            height: "auto",
            // backgroundImage: "url(" + pattern + ")",
        },
        spaceBar: {
            width: "auto",
            height: "50px",
        },
        smallSpaceBar: {
            width: "auto",
            height: "20px",
        },
        appBar: {
            width: "1440px",
            height: "90px",
            margin: "auto",
            customize: {
                width:"14.285%",
                height: "70px",
                display: "inline-flex",
            },
            apps: {
                width:"14.285%",
                height: "70px",
                display: "inline-flex",
            },
            stories: {
                width:"14.285%",
                height: "70px",
                display: "inline-flex",
            },
            gstickers: {
                width:"14.285%",
                height: "70px",
                display: "inline-flex",
                margin: "auto",
                padding: "auto",
                background: {
                    width: "100%",
                    height: "100%",
                    borderRadius: "11.7px",
                    backgroundColor: "#ffffff",
                    marginTop: "0px",
                },
                image: {

                    width: "164px",
                    objectFit: "contain",
                    marginLeft: "10%",
                    marginTop: "8%",
                    display: "inline-flex",
                },
                logoImage: {
                    width: "90%",
                    objectFit: "contain",
                    marginTop: "3px",
                    marginBottom: "3px",
                    display: "inline-flex",
                },
            },
            forCreators: {
                width:"14.285%",
                height: "70px",
                display: "inline-flex",
            },
            forBrands: {
                width:"14.285%",
                height: "70px",
                display: "inline-flex",
            },
            merch: {
                width:"14.285%",
                height: "70px",
                display: "inline-flex",
            },
            shadowText: {
                fontFamily: "Montserrat",
                fontSize: "24px",
                fontWeight: "800",
                letterSpacing: "-1.5px",
                margin: "auto",
                color: "#ffffff",
                textShadow: "0 1px 6px rgba(0, 0, 0, 0.5)",
            },
            text: {
                fontFamily: "Montserrat",
                fontSize: "24px",
                fontWeight: "800",
                letterSpacing: "-1.5px",
                margin: "auto",
                color: "#ffffff",
            },
            smallShadowText: {
                fontFamily: "Montserrat",
                fontSize: "14px",
                fontWeight: "800",
                letterSpacing: "-1.5px",
                margin: "auto",
                color: "#ffffff",
                textShadow: "0 1px 6px rgba(0, 0, 0, 0.5)",
            },
            smallText: {
                fontFamily: "Montserrat",
                fontSize: "14px",
                fontWeight: "800",
                letterSpacing: "-1.5px",
                margin: "auto",
                color: "#ffffff",
            }
        },
        bigText: {
            width: "70%",
            height: "auto",
            fontFamily: "Montserrat",
            fontSize: "40px",
            fontWeight: "bold",
            letterSpacing: "-2.5px",
            textAlign: "center",
            color: "#ffffff",
            textShadow: "0 1px 2px rgba(0, 0, 0, 0.5)",
            marginBottom: "20px",
            marginLeft: "auto",
            marginRight: "auto",
            objectFit: "contain",
            display: "block",
        },
        subText: {
            width: "70%",
            height: "auto",
            fontFamily: "Montserrat",
            fontSize: "30px",
            letterSpacing: "-2px",
            textAlign: "center",
            color: "#ffffff",
            textShadow: "0 1px 2px rgba(0, 0, 0, 0.5)",
            marginBottom: "20px",
            marginLeft: "auto",
            marginRight: "auto",
            objectFit: "contain",
            display: "block",
        },
        bigText_forSmallScreens: {
            width: "70%",
            height: "auto",
            fontFamily: "Montserrat",
            fontSize: "30px",
            fontWeight: "bold",
            letterSpacing: "-2.5px",
            textAlign: "center",
            color: "#ffffff",
            textShadow: "0 1px 2px rgba(0, 0, 0, 0.5)",
            marginBottom: "20px",
            marginLeft: "auto",
            marginRight: "auto",
            objectFit: "contain",
            display: "block",
        },
        subText_forSmallScreens: {
            width: "70%",
            height: "auto",
            fontFamily: "Montserrat",
            fontSize: "25px",
            letterSpacing: "-2px",
            textAlign: "center",
            color: "#ffffff",
            textShadow: "0 1px 2px rgba(0, 0, 0, 0.5)",
            marginBottom: "20px",
            marginLeft: "auto",
            marginRight: "auto",
            objectFit: "contain",
            display: "block",
        },
        download: {
            width: "257px",
            height: "37px",
            fontFamily: "Montserrat",
            fontSize: "30px",
            fontWeight: "bold",
            letterSpacing: "-1.8px",
            textAlign: "center",
            color: "#ffffff",
        },
        appBadges: {
            width: "90%",
            height: "auto",
            marginTop: "5px",
            marginBottom: "5px",
            marginRight: "5%",
            marginLeft: "5%",
        },
    },

    variableHeader2: {
        background: {
            height: "auto",
            backgroundImage: "linear-gradient(to bottom, #df5a34, #8651aa)",
        },
        pattern: {
            width: "100%",
            height: "auto",
            // backgroundImage: "url(" + pattern + ")",
        },
        spaceBar: {
            width: "auto",
            height: "50px",
        },
        smallSpaceBar: {
            width: "auto",
            height: "20px",
        },
        bigText: {
            // width: "70%",
            height: "auto",
            fontFamily: "Montserrat",
            // fontSize: "40px",
            fontWeight: "bold",
            letterSpacing: "-2.5px",
            textAlign: "center",
            color: "#ffffff",
            textShadow: "0 1px 2px rgba(0, 0, 0, 0.5)",
            marginBottom: "20px",
            marginLeft: "auto",
            marginRight: "auto",
            objectFit: "contain",
            display: "block",
        },
        subText: {
            width: "70%",
            height: "auto",
            fontFamily: "Montserrat",
            fontSize: "30px",
            // fontWeight: "bold",
            letterSpacing: "-2px",
            textAlign: "center",
            color: "#ffffff",
            textShadow: "0 1px 2px rgba(0, 0, 0, 0.5)",
            marginBottom: "20px",
            marginLeft: "auto",
            marginRight: "auto",
            objectFit: "contain",
            display: "block",
        },
    },

    
}
